name: Run License Tests
on:
  workflow_dispatch:
  pull_request:
jobs:
  license_tests:
    uses: neongeckocom/.github/.github/workflows/license_tests.yml@master
    with:
      packages-exclude: '^(precise-runner|fann2|tqdm|bs4|neon-core|nvidia|neon-skill|bitstruct).*'